# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'about.ui'
#
# Created: Mon May 10 22:27:06 2010
#      by: PyQt4 UI code generator 4.7.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_AboutDialog(object):
    def setupUi(self, AboutDialog):
        AboutDialog.setObjectName("AboutDialog")
        AboutDialog.resize(324, 277)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AboutDialog.sizePolicy().hasHeightForWidth())
        AboutDialog.setSizePolicy(sizePolicy)
        AboutDialog.setMinimumSize(QtCore.QSize(324, 241))
        AboutDialog.setMaximumSize(QtCore.QSize(99999, 99999))
        AboutDialog.setWhatsThis("")
        AboutDialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        AboutDialog.setModal(True)
        self.name_version_label = QtGui.QLabel(AboutDialog)
        self.name_version_label.setGeometry(QtCore.QRect(10, 75, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setWeight(75)
        font.setBold(True)
        self.name_version_label.setFont(font)
        self.name_version_label.setText("TortoiseHg (version %s)")
        self.name_version_label.setAlignment(QtCore.Qt.AlignCenter)
        self.name_version_label.setObjectName("name_version_label")
        self.libs_label = QtGui.QLabel(AboutDialog)
        self.libs_label.setGeometry(QtCore.QRect(10, 100, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.libs_label.setFont(font)
        self.libs_label.setAlignment(QtCore.Qt.AlignCenter)
        self.libs_label.setObjectName("libs_label")
        self.download_label = QtGui.QLabel(AboutDialog)
        self.download_label.setGeometry(QtCore.QRect(10, 180, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.download_label.setFont(font)
        self.download_label.setAlignment(QtCore.Qt.AlignCenter)
        self.download_label.setObjectName("download_label")
        self.copyright_label = QtGui.QLabel(AboutDialog)
        self.copyright_label.setGeometry(QtCore.QRect(10, 130, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.copyright_label.setFont(font)
        self.copyright_label.setAlignment(QtCore.Qt.AlignCenter)
        self.copyright_label.setObjectName("copyright_label")
        self.close_button = QtGui.QPushButton(AboutDialog)
        self.close_button.setGeometry(QtCore.QRect(235, 240, 75, 23))
        self.close_button.setObjectName("close_button")
        self.license_button = QtGui.QPushButton(AboutDialog)
        self.license_button.setGeometry(QtCore.QRect(15, 240, 75, 23))
        self.license_button.setObjectName("license_button")
        self.download_url_label = QtGui.QLabel(AboutDialog)
        self.download_url_label.setGeometry(QtCore.QRect(10, 200, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.download_url_label.setFont(font)
        self.download_url_label.setMouseTracking(True)
        self.download_url_label.setFrameShape(QtGui.QFrame.NoFrame)
        self.download_url_label.setFrameShadow(QtGui.QFrame.Plain)
        self.download_url_label.setText("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><a href=\"http://thg_download_url\"><span style=\" text-decoration: underline; color:#0000ff;\">http://thg-download-url</span></a></p></body></html>")
        self.download_url_label.setAlignment(QtCore.Qt.AlignCenter)
        self.download_url_label.setOpenExternalLinks(False)
        self.download_url_label.setObjectName("download_url_label")
        self.courtesy_label = QtGui.QLabel(AboutDialog)
        self.courtesy_label.setGeometry(QtCore.QRect(10, 150, 301, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.courtesy_label.setFont(font)
        self.courtesy_label.setAlignment(QtCore.Qt.AlignCenter)
        self.courtesy_label.setObjectName("courtesy_label")
        self.logo_label = QtGui.QLabel(AboutDialog)
        self.logo_label.setGeometry(QtCore.QRect(116, 16, 92, 50))
        self.logo_label.setAutoFillBackground(True)
        self.logo_label.setFrameShape(QtGui.QFrame.NoFrame)
        self.logo_label.setText("")
        self.logo_label.setAlignment(QtCore.Qt.AlignCenter)
        self.logo_label.setObjectName("logo_label")
        self.actionVisitDownloadSite = QtGui.QAction(AboutDialog)
        self.actionVisitDownloadSite.setCheckable(True)
        self.actionVisitDownloadSite.setObjectName("actionVisitDownloadSite")
        self.actionshowLicense = QtGui.QAction(AboutDialog)
        self.actionshowLicense.setCheckable(True)
        self.actionshowLicense.setObjectName("actionshowLicense")

        self.retranslateUi(AboutDialog)
        QtCore.QObject.connect(self.close_button, QtCore.SIGNAL("clicked()"), AboutDialog.close)
        QtCore.QObject.connect(self.download_url_label, QtCore.SIGNAL("linkActivated(QString)"), AboutDialog.actionVisitDownloadSite)
        QtCore.QObject.connect(self.license_button, QtCore.SIGNAL("clicked()"), AboutDialog.actionShowLicense)
        QtCore.QMetaObject.connectSlotsByName(AboutDialog)

    def retranslateUi(self, AboutDialog):
        AboutDialog.setWindowTitle(QtGui.QApplication.translate("AboutDialog", "About TortoiseHg", None, QtGui.QApplication.UnicodeUTF8))
        self.libs_label.setText(QtGui.QApplication.translate("AboutDialog", "with Mercurial-%s, Python-%s, PyQt4-%s, Qt-%s", None, QtGui.QApplication.UnicodeUTF8))
        self.download_label.setText(QtGui.QApplication.translate("AboutDialog", "A new version of TortoisHg is ready for download!", None, QtGui.QApplication.UnicodeUTF8))
        self.copyright_label.setText(QtGui.QApplication.translate("AboutDialog", "Copyright 2008-2010 Steve Borho and others", None, QtGui.QApplication.UnicodeUTF8))
        self.close_button.setText(QtGui.QApplication.translate("AboutDialog", "&Close", None, QtGui.QApplication.UnicodeUTF8))
        self.license_button.setText(QtGui.QApplication.translate("AboutDialog", "&License", None, QtGui.QApplication.UnicodeUTF8))
        self.courtesy_label.setText(QtGui.QApplication.translate("AboutDialog", "Several icons are courtesy of the TortoiseSVN project", None, QtGui.QApplication.UnicodeUTF8))
        self.actionVisitDownloadSite.setText(QtGui.QApplication.translate("AboutDialog", "visitDownloadSite", None, QtGui.QApplication.UnicodeUTF8))
        self.actionshowLicense.setText(QtGui.QApplication.translate("AboutDialog", "showLicense", None, QtGui.QApplication.UnicodeUTF8))
        self.actionshowLicense.setToolTip(QtGui.QApplication.translate("AboutDialog", "showLicense", None, QtGui.QApplication.UnicodeUTF8))

